airplane:
  std: [0.9208, 0.4103, 0.8857, 1.0000, 1.0000, 1.0000]
  mean: [-0.4604, -0.2052, -0.4429,  0.0000,  0.0000,  0.0000]
car:
  std: [0.6137, 0.4152, 0.9569, 1.0000, 1.0000, 1.0000]
  mean: [-0.3068, -0.2076, -0.4784,  0.0000,  0.0000,  0.0000]
